Update optimus-cli script

diff --git a/optimus-cli b/optimus-cli
--- a/optimus-cli
+++ b/optimus-cli
@@ -4,9 +4,36 @@ INSTALL_DIRECTORY=".cli"
 CLI_ENTRY_POINT="python3 ./${INSTALL_DIRECTORY}/cli.py"
 REPOSITORY="git@github.com:optimuscms/optimus-cli.git"
 
+# Ensures the necessary dependencies are available
+check_dependencies() {
+    hash php-cs-fixer 2>/dev/null || {
+        echo >&2 "php-cs-fixer is required but not available, aborting...";
+        exit 1;
+    }
+
+    hash yarn 2>/dev/null || {
+        echo >&2 "yarn is required but not available, aborting...";
+        exit 1;
+    }
+
+    hash python3 2>/dev/null || {
+        echo >&2 "python3 is required but not available, aborting...";
+        exit 1;
+    }
+
+    if [[ $(python3 -c 'import sys; print(sys.version_info[1] >= 6)') != 'True' ]]; then
+        echo "Python version >= 3.6 required, aborting...";
+        exit 1;
+    fi
+
+    if [ ! -d 'node_modules' ]; then
+    	echo "Please run 'yarn install' before using optimus-cli.";
+    	exit 1;
+    fi
+}
+
 # Outputs usage instructions to the console
 print_help () {
-    echo "";
     echo "Usage:";
     echo "  optimus-cli <command>"
     echo "";
@@ -17,28 +44,43 @@ print_help () {
 
 # Clones the cli repository and removes .git, preventing nested repositories.
 update_cli () {
-    echo "";
-    echo "Updating optimus-cli...";
+    echo "Downloading latest Optimus CLI...";
 
-    rm -rf $INSTALL_DIRECTORY
+    rm -rf ./${INSTALL_DIRECTORY}
 
-    git clone --quiet $REPOSITORY $INSTALL_DIRECTORY
-    rm -rf ./$INSTALL_DIRECTORY/.git
+    git clone --quiet ${REPOSITORY} ${INSTALL_DIRECTORY}
+    cd ./${INSTALL_DIRECTORY}
+    rm -rf .git
 
-    echo "Successfully updated optimus-cli to the latest version";
+    echo "Installing Optimus CLI..."
+
+    python3 -m venv ./.venv/
+    source ./.venv/bin/activate;
+    pip3 install -r requirements.txt &>/dev/null
+
+    echo "Successfully updated Optimus CLI to the latest version";
 }
 
-if [ "$#" -lt 1 ]
+echo "";
+check_dependencies;
+
+if [ "$#" -lt 1 ];
 then
     print_help;
 
-elif [ $1 = "update" ]
+elif [ $1 = "update" ];
 then
-    update_cli
+    update_cli;
 
-elif [[ ! -d $INSTALL_DIRECTORY ]]
+elif [[ ! -d $INSTALL_DIRECTORY ]];
 then
-    echo "optimus-cli files not found, have you run optimus-cli update?";
+    echo "Optimus CLI files not found, have you run optimus-cli update?";
 else
-    eval "${CLI_ENTRY_POINT} $@"
+    if [ ! -d "${INSTALL_DIRECTORY}/.venv" ]; then
+    	echo "Python virtual environment not found, have you run optimus-cli update?";
+    	exit 1;
+    fi
+
+    source ./${INSTALL_DIRECTORY}/.venv/bin/activate;
+    eval "${CLI_ENTRY_POINT} $@";
 fi
